[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 10000
gas_reports = ["*"]
ffi = true
[fmt]
bracket_spacing = true
line_length = 70
number_underscore = "thousands"
wrap_comments = false
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
fantom = "${FANTOM_RPC_URL}"
avalanche = "${AVALANCHE_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
bsc = "${BSC_RPC_URL}"
cronos = "${CRONOS_RPC_URL}"
base = "${BASE_RPC_URL}"
gnosis = "${GNOSIS_RPC_URL}"
fraxtal = "${FRAXTAL_RPC_URL}"
[etherscan]
mainnet = { key = "${MAINNET_ETHERSCAN_API_KEY}" }
fantom = { key = "${FANTOM_ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGON_ETHERSCAN_API_KEY}" }
avalanche = { key = "${AVALANCHE_ETHERSCAN_API_KEY}" }
optimism = { key = "${OPTIMISM_ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ARBITRUM_ETHERSCAN_API_KEY}" }
bsc = { key = "${BSC_ETHERSCAN_API_KEY}" }
cronos = { key = "${CRONOS_ETHERSCAN_API_KEY}" }
base = { key = "${BASE_ETHERSCAN_API_KEY}" }
gnosis = { key = "${GNOSIS_ETHERSCAN_API_KEY}", url = "https://api.gnosisscan.io/api" }
fraxtal = { key = "${FRAXTAL_ETHERSCAN_API_KEY}" }
[fuzz]
runs = 16


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
